spring:
  application:
    name: rotanava-boot-module-system-websocket
  redis:
    database: 1
    host: rotanavaredis
    password: DoDRXCvBXu
    port: 6379
    timeout: 7000
  jedis:
    pool:
      max-active: 10
      max-idle: 20
      max-wait: 3000
      min-idle: 2
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: RN2020.
    virtual-host: /
    publisher-confirm-type: correlated
rotanava:
  socket:
    port: 10504
    scan: com.rotanava.*
server:
  port: 7032