spring:
  application:
    name: rotanava-boot-module-system-websocket
  redis:
    database: 4
    host: 127.0.0.1
    password: password
    port: 6379
    timeout: 7000
  jedis:
    pool:
      max-active: 10
      max-idle: 20
      max-wait: 3000
      min-idle: 2
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: password
    virtual-host: /
    publisher-confirm-type: correlated
rotanava:
  socket:
    port: 30502
    scan: com.rotanava.*
server:
  port: 7032