minio:
  accessKey: admin
  endpoint: http://127.0.0.1:9000
  secretKey: admin123456
rotanava:
  uploadType: minio
  xxljob:
    # 是否开启
    enabled: true
    #### xxl-job admin address list：调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
    adminAddresses: http://127.0.0.1:9081/xxl-job-admin
    ### xxl-job executor address：执行器"AppName"和地址信息配置：AppName执行器心跳注册分组依据；地址信息用于"调度中心请求并触发任务"和"执行器注册"
    #。执行器默认端口为9999，执行器IP默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用。单机部署多个执行器时，注意要配置不同执行器端口；
    appname: ${spring.application.name}
    ip: 127.0.0.1
    port: 30007
    ### xxl-job, access token：执行器通讯TOKEN，非空时启用
    accessToken:
server:
  port: 8896
spring:
  application:
    name: rotanava-boot-module-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 5
      removeAbandoned: false
      removeAbandonedTimeout: 1800
      keep-alive: true
      validation-query: select 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
    filters: stat,wall,log4j
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/rn_base_sys?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
  mail:
    host: mail_host
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: mail_username
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 10
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    password: password
    port: 6379
    timeout: 7000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: password
    virtual-host: /
    publisher-confirm-type: correlated
mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  enable: true
dubbo:
  consumer:
    check: false
    retries: 0
    validation: true
  protocol:
    name: dubbo
    port: -1
  provider:
    retries: 0
    timeout: 30000
    #解决自定义异常丢失
    filter: -exception
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
  application:
    name: rotanava-boot-module-system
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    prefer-ip-address: true
opentracing:
  #  https://github.com/opentracing-contrib/java-spring-jaeger
  jaeger:
    enabled: true
    udp-sender:
      host: 192.168.0.165
      port: 6831
    #    概率采样器 其中value是之间0.0（没有采样）和1.0（每个请求的采样）
    probabilistic-sampler:
      sampling-rate: 1.0
    #   不打印到控制台
    log-spans: false
logging:
  config: classpath:logback-dev.xml