#所有权：福建新航物联网科技有限公司
#日期：2022年01月19日
#版本号
version: '2.1'
services:
  zookeeper:
    image:  registry.cn-hangzhou.aliyuncs.com/rotanova/zookeeper:v1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  eureka:  # 指定服务名称
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/eureka-centre:v2
    restart: always
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  rotanavaredis:  # 指定服务名称
    image: redis:latest
    container_name: rotanavaredis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      rotanova_bridge:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/config:/root/.minio
      - ./minio/data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ':9001' /data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  rotanavamysql:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-mysql:0.0.2
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PWD}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      rotanova_bridge:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  rotanava-boot-module-system:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-boot-module-system:1.0.14
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - minioAccessKey=${MINIO_ACCESS_KEY}
      - minioEndpoint=${MINIO_ENDPOINT}
      - minioSecretKey=${MINIO_SECRET_KEY}
      - datasourcePwd=${DATASOURCE_PWD}
      - rabbitmqPwd=${RABBITMQ_DEFAULT_PASS}
      - rabbitmqUser=${RABBITMQ_DEFAULT_USER}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    depends_on:
      rotanavamysql:
        condition: service_healthy
    networks:
      rotanova_bridge:
  rotanava-boot-module-dbapi:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-boot-module-dbapi:1.0.2
    restart: always
    ports:
      - "7052:7052"    
    environment:
      - TZ=Asia/Shanghai
      - datasourcePwd=${DATASOURCE_PWD}
      - rabbitmqPwd=${RABBITMQ_DEFAULT_PASS}
      - rabbitmqUser=${RABBITMQ_DEFAULT_USER}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:      
  rotanava-boot-module-system-websocket:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-boot-module-system-websocket:0.0.5
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "10504:10504"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  rotanava-boot-module-xxljob:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-boot-module-xxljob:1.0.0
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - datasourcePwd=${DATASOURCE_PWD}
    ports:
      - "9080:9080"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  rotanava-boot-module-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanava-boot-module-gateway:1.0.0
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8899:8083"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/rotanova/rotanova-nginx:v1.0.85.5
    restart: always
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      rotanova_bridge:
networks:
  rotanova_bridge: